logging:
  file:
    name: ./logs/run.log
  group:
    # 方式1：通过组来设置日志级别 可以多个多个逗号隔开
    dynamic: com.hm.springboot.logging.practice.controller,com.hm.springboot.logging.practice.rest
  level:
    dynamic: info
    # 方式2：直接设置包的日志级别
    com.hm.springboot.logging.practice: debug

management:
  endpoints:
    web:
      exposure:
        include: loggers
  